spring:
  h2:
    console: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    sqlScriptEncoding: UTF-8
  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

#    hibernate:
#      ddl-auto: create
#        javax:
#          persistence:
#            schema-generation:
#              scripts:
#                action: create
#                  create-target: create.sql
#                  create-source: metadata


